### ISSUE TITLE
Is it possible to add offset to the animation moves?

### ISSUE THREAD

**Issue by Ax0elz** [TesteurManiak/flutter_map_animations#22] opened 2023-10-24 02:55 UTC
Hi, was wondering if it would be possible to add an offset like the mapController. I often want to animate to somewhere but want it to get with the an offset by px. 

Currently only the main map controller has the offset

**Comment by TesteurManiak** [comment] 2023-10-24 07:04
Duplicate of #19 
Was fixed in #20 
You can already use it by pointing on the `master` branch of the repo.

**Closed by TesteurManiak** 2023-10-24 07:04 UTC
